/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as ParaEmpresasRouteImport } from './routes/para-empresas'
import { Route as FreelasRouteImport } from './routes/freelas'
import { Route as FreelancerRouteImport } from './routes/freelancer'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as CandidatoRouteImport } from './routes/candidato'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnuncieRouteImport } from './routes/anuncie'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VagasIndexRouteImport } from './routes/vagas.index'
import { Route as PreviewIndexRouteImport } from './routes/preview.index'
import { Route as FreelasIndexRouteImport } from './routes/freelas.index'
import { Route as FreelancerIndexRouteImport } from './routes/freelancer.index'
import { Route as CandidatoIndexRouteImport } from './routes/candidato.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VagasPjRouteImport } from './routes/vagas.pj'
import { Route as VagasEstagioRouteImport } from './routes/vagas.estagio'
import { Route as VagasCltRouteImport } from './routes/vagas.clt'
import { Route as VagasSlugRouteImport } from './routes/vagas.$slug'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as ProfissionaisSlugRouteImport } from './routes/profissionais.$slug'
import { Route as PreviewStyleRouteImport } from './routes/preview.$style'
import { Route as FreelancerPortfolioRouteImport } from './routes/freelancer.portfolio'
import { Route as FreelancerPerfilRouteImport } from './routes/freelancer.perfil'
import { Route as FreelancerOrcamentosRouteImport } from './routes/freelancer.orcamentos'
import { Route as EmpresaVerificacaoRouteImport } from './routes/empresa.verificacao'
import { Route as EmpresaPaginaRouteImport } from './routes/empresa.pagina'
import { Route as EmpresaNovaVagaRouteImport } from './routes/empresa.nova-vaga'
import { Route as EmpresaMinhasVagasRouteImport } from './routes/empresa.minhas-vagas'
import { Route as CvSlugRouteImport } from './routes/cv.$slug'
import { Route as CandidatoVagasRouteImport } from './routes/candidato.vagas'
import { Route as CandidatoSalvasRouteImport } from './routes/candidato.salvas'
import { Route as CandidatoCurriculoRouteImport } from './routes/candidato.curriculo'
import { Route as CandidatoCandidaturasRouteImport } from './routes/candidato.candidaturas'
import { Route as CandidatoAlertasRouteImport } from './routes/candidato.alertas'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminVerificacoesRouteImport } from './routes/admin.verificacoes'
import { Route as AdminVagasRouteImport } from './routes/admin.vagas'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminAnunciosRouteImport } from './routes/admin.anuncios'
import { Route as FreelasPHandleRouteImport } from './routes/freelas.p.$handle'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'
import { Route as ApiPublicPainelMigracaoRouteImport } from './routes/api/public/painel-migracao'
import { Route as ApiPublicMigrateSqlRouteImport } from './routes/api/public/migrate-sql'
import { Route as ApiPublicAsaasWebhookRouteImport } from './routes/api/public/asaas-webhook'
import { Route as AdminBlogNovoRouteImport } from './routes/admin.blog.novo'
import { Route as AdminBlogIdRouteImport } from './routes/admin.blog.$id'
import { Route as ApiPublicPushRenewRouteImport } from './routes/api/public/push.renew'
import { Route as ApiPublicCronReindexVagasRouteImport } from './routes/api/public/cron/reindex-vagas'
import { Route as ApiPublicCronReindexGoogleRouteImport } from './routes/api/public/cron.reindex-google'
import { Route as ApiPublicCronGerarPostRouteImport } from './routes/api/public/cron.gerar-post'
import { Route as ApiPublicCronEmpresaDailyRouteImport } from './routes/api/public/cron/empresa-daily'
import { Route as ApiPublicBlogIngestRouteImport } from './routes/api/public/blog.ingest'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaEmpresasRoute = ParaEmpresasRouteImport.update({
  id: '/para-empresas',
  path: '/para-empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelasRoute = FreelasRouteImport.update({
  id: '/freelas',
  path: '/freelas',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancerRoute = FreelancerRouteImport.update({
  id: '/freelancer',
  path: '/freelancer',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatoRoute = CandidatoRouteImport.update({
  id: '/candidato',
  path: '/candidato',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnuncieRoute = AnuncieRouteImport.update({
  id: '/anuncie',
  path: '/anuncie',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VagasIndexRoute = VagasIndexRouteImport.update({
  id: '/vagas/',
  path: '/vagas/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewIndexRoute = PreviewIndexRouteImport.update({
  id: '/preview/',
  path: '/preview/',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelasIndexRoute = FreelasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FreelasRoute,
} as any)
const FreelancerIndexRoute = FreelancerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FreelancerRoute,
} as any)
const CandidatoIndexRoute = CandidatoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CandidatoRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const VagasPjRoute = VagasPjRouteImport.update({
  id: '/vagas/pj',
  path: '/vagas/pj',
  getParentRoute: () => rootRouteImport,
} as any)
const VagasEstagioRoute = VagasEstagioRouteImport.update({
  id: '/vagas/estagio',
  path: '/vagas/estagio',
  getParentRoute: () => rootRouteImport,
} as any)
const VagasCltRoute = VagasCltRouteImport.update({
  id: '/vagas/clt',
  path: '/vagas/clt',
  getParentRoute: () => rootRouteImport,
} as any)
const VagasSlugRoute = VagasSlugRouteImport.update({
  id: '/vagas/$slug',
  path: '/vagas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfissionaisSlugRoute = ProfissionaisSlugRouteImport.update({
  id: '/profissionais/$slug',
  path: '/profissionais/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewStyleRoute = PreviewStyleRouteImport.update({
  id: '/preview/$style',
  path: '/preview/$style',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancerPortfolioRoute = FreelancerPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => FreelancerRoute,
} as any)
const FreelancerPerfilRoute = FreelancerPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => FreelancerRoute,
} as any)
const FreelancerOrcamentosRoute = FreelancerOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => FreelancerRoute,
} as any)
const EmpresaVerificacaoRoute = EmpresaVerificacaoRouteImport.update({
  id: '/verificacao',
  path: '/verificacao',
  getParentRoute: () => EmpresaRoute,
} as any)
const EmpresaPaginaRoute = EmpresaPaginaRouteImport.update({
  id: '/pagina',
  path: '/pagina',
  getParentRoute: () => EmpresaRoute,
} as any)
const EmpresaNovaVagaRoute = EmpresaNovaVagaRouteImport.update({
  id: '/nova-vaga',
  path: '/nova-vaga',
  getParentRoute: () => EmpresaRoute,
} as any)
const EmpresaMinhasVagasRoute = EmpresaMinhasVagasRouteImport.update({
  id: '/minhas-vagas',
  path: '/minhas-vagas',
  getParentRoute: () => EmpresaRoute,
} as any)
const CvSlugRoute = CvSlugRouteImport.update({
  id: '/cv/$slug',
  path: '/cv/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatoVagasRoute = CandidatoVagasRouteImport.update({
  id: '/vagas',
  path: '/vagas',
  getParentRoute: () => CandidatoRoute,
} as any)
const CandidatoSalvasRoute = CandidatoSalvasRouteImport.update({
  id: '/salvas',
  path: '/salvas',
  getParentRoute: () => CandidatoRoute,
} as any)
const CandidatoCurriculoRoute = CandidatoCurriculoRouteImport.update({
  id: '/curriculo',
  path: '/curriculo',
  getParentRoute: () => CandidatoRoute,
} as any)
const CandidatoCandidaturasRoute = CandidatoCandidaturasRouteImport.update({
  id: '/candidaturas',
  path: '/candidaturas',
  getParentRoute: () => CandidatoRoute,
} as any)
const CandidatoAlertasRoute = CandidatoAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => CandidatoRoute,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerificacoesRoute = AdminVerificacoesRouteImport.update({
  id: '/admin/verificacoes',
  path: '/admin/verificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVagasRoute = AdminVagasRouteImport.update({
  id: '/admin/vagas',
  path: '/admin/vagas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/admin/blog',
  path: '/admin/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnunciosRoute = AdminAnunciosRouteImport.update({
  id: '/admin/anuncios',
  path: '/admin/anuncios',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelasPHandleRoute = FreelasPHandleRouteImport.update({
  id: '/p/$handle',
  path: '/p/$handle',
  getParentRoute: () => FreelasRoute,
} as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPainelMigracaoRoute = ApiPublicPainelMigracaoRouteImport.update({
  id: '/api/public/painel-migracao',
  path: '/api/public/painel-migracao',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMigrateSqlRoute = ApiPublicMigrateSqlRouteImport.update({
  id: '/api/public/migrate-sql',
  path: '/api/public/migrate-sql',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAsaasWebhookRoute = ApiPublicAsaasWebhookRouteImport.update({
  id: '/api/public/asaas-webhook',
  path: '/api/public/asaas-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogNovoRoute = AdminBlogNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminBlogRoute,
} as any)
const ApiPublicPushRenewRoute = ApiPublicPushRenewRouteImport.update({
  id: '/api/public/push/renew',
  path: '/api/public/push/renew',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronReindexVagasRoute =
  ApiPublicCronReindexVagasRouteImport.update({
    id: '/api/public/cron/reindex-vagas',
    path: '/api/public/cron/reindex-vagas',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronReindexGoogleRoute =
  ApiPublicCronReindexGoogleRouteImport.update({
    id: '/api/public/cron/reindex-google',
    path: '/api/public/cron/reindex-google',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronGerarPostRoute = ApiPublicCronGerarPostRouteImport.update({
  id: '/api/public/cron/gerar-post',
  path: '/api/public/cron/gerar-post',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronEmpresaDailyRoute =
  ApiPublicCronEmpresaDailyRouteImport.update({
    id: '/api/public/cron/empresa-daily',
    path: '/api/public/cron/empresa-daily',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBlogIngestRoute = ApiPublicBlogIngestRouteImport.update({
  id: '/api/public/blog/ingest',
  path: '/api/public/blog/ingest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anuncie': typeof AnuncieRoute
  '/auth': typeof AuthRoute
  '/cadastro': typeof CadastroRoute
  '/candidato': typeof CandidatoRouteWithChildren
  '/categorias': typeof CategoriasRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/empresa': typeof EmpresaRouteWithChildren
  '/freelancer': typeof FreelancerRouteWithChildren
  '/freelas': typeof FreelasRouteWithChildren
  '/para-empresas': typeof ParaEmpresasRoute
  '/perfil': typeof PerfilRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/admin/anuncios': typeof AdminAnunciosRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/vagas': typeof AdminVagasRoute
  '/admin/verificacoes': typeof AdminVerificacoesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/c/$slug': typeof CSlugRoute
  '/candidato/alertas': typeof CandidatoAlertasRoute
  '/candidato/candidaturas': typeof CandidatoCandidaturasRoute
  '/candidato/curriculo': typeof CandidatoCurriculoRoute
  '/candidato/salvas': typeof CandidatoSalvasRoute
  '/candidato/vagas': typeof CandidatoVagasRoute
  '/cv/$slug': typeof CvSlugRoute
  '/empresa/minhas-vagas': typeof EmpresaMinhasVagasRoute
  '/empresa/nova-vaga': typeof EmpresaNovaVagaRoute
  '/empresa/pagina': typeof EmpresaPaginaRoute
  '/empresa/verificacao': typeof EmpresaVerificacaoRoute
  '/freelancer/orcamentos': typeof FreelancerOrcamentosRoute
  '/freelancer/perfil': typeof FreelancerPerfilRoute
  '/freelancer/portfolio': typeof FreelancerPortfolioRoute
  '/preview/$style': typeof PreviewStyleRoute
  '/profissionais/$slug': typeof ProfissionaisSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/vagas/$slug': typeof VagasSlugRoute
  '/vagas/clt': typeof VagasCltRoute
  '/vagas/estagio': typeof VagasEstagioRoute
  '/vagas/pj': typeof VagasPjRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/candidato/': typeof CandidatoIndexRoute
  '/freelancer/': typeof FreelancerIndexRoute
  '/freelas/': typeof FreelasIndexRoute
  '/preview/': typeof PreviewIndexRoute
  '/vagas/': typeof VagasIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/novo': typeof AdminBlogNovoRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/public/migrate-sql': typeof ApiPublicMigrateSqlRoute
  '/api/public/painel-migracao': typeof ApiPublicPainelMigracaoRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/freelas/p/$handle': typeof FreelasPHandleRoute
  '/api/public/blog/ingest': typeof ApiPublicBlogIngestRoute
  '/api/public/cron/empresa-daily': typeof ApiPublicCronEmpresaDailyRoute
  '/api/public/cron/gerar-post': typeof ApiPublicCronGerarPostRoute
  '/api/public/cron/reindex-google': typeof ApiPublicCronReindexGoogleRoute
  '/api/public/cron/reindex-vagas': typeof ApiPublicCronReindexVagasRoute
  '/api/public/push/renew': typeof ApiPublicPushRenewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anuncie': typeof AnuncieRoute
  '/auth': typeof AuthRoute
  '/cadastro': typeof CadastroRoute
  '/categorias': typeof CategoriasRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/empresa': typeof EmpresaRouteWithChildren
  '/para-empresas': typeof ParaEmpresasRoute
  '/perfil': typeof PerfilRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/admin/anuncios': typeof AdminAnunciosRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/vagas': typeof AdminVagasRoute
  '/admin/verificacoes': typeof AdminVerificacoesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/c/$slug': typeof CSlugRoute
  '/candidato/alertas': typeof CandidatoAlertasRoute
  '/candidato/candidaturas': typeof CandidatoCandidaturasRoute
  '/candidato/curriculo': typeof CandidatoCurriculoRoute
  '/candidato/salvas': typeof CandidatoSalvasRoute
  '/candidato/vagas': typeof CandidatoVagasRoute
  '/cv/$slug': typeof CvSlugRoute
  '/empresa/minhas-vagas': typeof EmpresaMinhasVagasRoute
  '/empresa/nova-vaga': typeof EmpresaNovaVagaRoute
  '/empresa/pagina': typeof EmpresaPaginaRoute
  '/empresa/verificacao': typeof EmpresaVerificacaoRoute
  '/freelancer/orcamentos': typeof FreelancerOrcamentosRoute
  '/freelancer/perfil': typeof FreelancerPerfilRoute
  '/freelancer/portfolio': typeof FreelancerPortfolioRoute
  '/preview/$style': typeof PreviewStyleRoute
  '/profissionais/$slug': typeof ProfissionaisSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/vagas/$slug': typeof VagasSlugRoute
  '/vagas/clt': typeof VagasCltRoute
  '/vagas/estagio': typeof VagasEstagioRoute
  '/vagas/pj': typeof VagasPjRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/candidato': typeof CandidatoIndexRoute
  '/freelancer': typeof FreelancerIndexRoute
  '/freelas': typeof FreelasIndexRoute
  '/preview': typeof PreviewIndexRoute
  '/vagas': typeof VagasIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/novo': typeof AdminBlogNovoRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/public/migrate-sql': typeof ApiPublicMigrateSqlRoute
  '/api/public/painel-migracao': typeof ApiPublicPainelMigracaoRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/freelas/p/$handle': typeof FreelasPHandleRoute
  '/api/public/blog/ingest': typeof ApiPublicBlogIngestRoute
  '/api/public/cron/empresa-daily': typeof ApiPublicCronEmpresaDailyRoute
  '/api/public/cron/gerar-post': typeof ApiPublicCronGerarPostRoute
  '/api/public/cron/reindex-google': typeof ApiPublicCronReindexGoogleRoute
  '/api/public/cron/reindex-vagas': typeof ApiPublicCronReindexVagasRoute
  '/api/public/push/renew': typeof ApiPublicPushRenewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anuncie': typeof AnuncieRoute
  '/auth': typeof AuthRoute
  '/cadastro': typeof CadastroRoute
  '/candidato': typeof CandidatoRouteWithChildren
  '/categorias': typeof CategoriasRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/empresa': typeof EmpresaRouteWithChildren
  '/freelancer': typeof FreelancerRouteWithChildren
  '/freelas': typeof FreelasRouteWithChildren
  '/para-empresas': typeof ParaEmpresasRoute
  '/perfil': typeof PerfilRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/admin/anuncios': typeof AdminAnunciosRoute
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/vagas': typeof AdminVagasRoute
  '/admin/verificacoes': typeof AdminVerificacoesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/c/$slug': typeof CSlugRoute
  '/candidato/alertas': typeof CandidatoAlertasRoute
  '/candidato/candidaturas': typeof CandidatoCandidaturasRoute
  '/candidato/curriculo': typeof CandidatoCurriculoRoute
  '/candidato/salvas': typeof CandidatoSalvasRoute
  '/candidato/vagas': typeof CandidatoVagasRoute
  '/cv/$slug': typeof CvSlugRoute
  '/empresa/minhas-vagas': typeof EmpresaMinhasVagasRoute
  '/empresa/nova-vaga': typeof EmpresaNovaVagaRoute
  '/empresa/pagina': typeof EmpresaPaginaRoute
  '/empresa/verificacao': typeof EmpresaVerificacaoRoute
  '/freelancer/orcamentos': typeof FreelancerOrcamentosRoute
  '/freelancer/perfil': typeof FreelancerPerfilRoute
  '/freelancer/portfolio': typeof FreelancerPortfolioRoute
  '/preview/$style': typeof PreviewStyleRoute
  '/profissionais/$slug': typeof ProfissionaisSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/vagas/$slug': typeof VagasSlugRoute
  '/vagas/clt': typeof VagasCltRoute
  '/vagas/estagio': typeof VagasEstagioRoute
  '/vagas/pj': typeof VagasPjRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/candidato/': typeof CandidatoIndexRoute
  '/freelancer/': typeof FreelancerIndexRoute
  '/freelas/': typeof FreelasIndexRoute
  '/preview/': typeof PreviewIndexRoute
  '/vagas/': typeof VagasIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/novo': typeof AdminBlogNovoRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/public/migrate-sql': typeof ApiPublicMigrateSqlRoute
  '/api/public/painel-migracao': typeof ApiPublicPainelMigracaoRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/freelas/p/$handle': typeof FreelasPHandleRoute
  '/api/public/blog/ingest': typeof ApiPublicBlogIngestRoute
  '/api/public/cron/empresa-daily': typeof ApiPublicCronEmpresaDailyRoute
  '/api/public/cron/gerar-post': typeof ApiPublicCronGerarPostRoute
  '/api/public/cron/reindex-google': typeof ApiPublicCronReindexGoogleRoute
  '/api/public/cron/reindex-vagas': typeof ApiPublicCronReindexVagasRoute
  '/api/public/push/renew': typeof ApiPublicPushRenewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anuncie'
    | '/auth'
    | '/cadastro'
    | '/candidato'
    | '/categorias'
    | '/como-funciona'
    | '/contato'
    | '/empresa'
    | '/freelancer'
    | '/freelas'
    | '/para-empresas'
    | '/perfil'
    | '/planos'
    | '/privacidade'
    | '/reset-password'
    | '/sitemap.xml'
    | '/termos'
    | '/admin/anuncios'
    | '/admin/blog'
    | '/admin/usuarios'
    | '/admin/vagas'
    | '/admin/verificacoes'
    | '/blog/$slug'
    | '/c/$slug'
    | '/candidato/alertas'
    | '/candidato/candidaturas'
    | '/candidato/curriculo'
    | '/candidato/salvas'
    | '/candidato/vagas'
    | '/cv/$slug'
    | '/empresa/minhas-vagas'
    | '/empresa/nova-vaga'
    | '/empresa/pagina'
    | '/empresa/verificacao'
    | '/freelancer/orcamentos'
    | '/freelancer/perfil'
    | '/freelancer/portfolio'
    | '/preview/$style'
    | '/profissionais/$slug'
    | '/u/$handle'
    | '/vagas/$slug'
    | '/vagas/clt'
    | '/vagas/estagio'
    | '/vagas/pj'
    | '/admin/'
    | '/blog/'
    | '/candidato/'
    | '/freelancer/'
    | '/freelas/'
    | '/preview/'
    | '/vagas/'
    | '/admin/blog/$id'
    | '/admin/blog/novo'
    | '/api/public/asaas-webhook'
    | '/api/public/migrate-sql'
    | '/api/public/painel-migracao'
    | '/api/public/track'
    | '/freelas/p/$handle'
    | '/api/public/blog/ingest'
    | '/api/public/cron/empresa-daily'
    | '/api/public/cron/gerar-post'
    | '/api/public/cron/reindex-google'
    | '/api/public/cron/reindex-vagas'
    | '/api/public/push/renew'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anuncie'
    | '/auth'
    | '/cadastro'
    | '/categorias'
    | '/como-funciona'
    | '/contato'
    | '/empresa'
    | '/para-empresas'
    | '/perfil'
    | '/planos'
    | '/privacidade'
    | '/reset-password'
    | '/sitemap.xml'
    | '/termos'
    | '/admin/anuncios'
    | '/admin/blog'
    | '/admin/usuarios'
    | '/admin/vagas'
    | '/admin/verificacoes'
    | '/blog/$slug'
    | '/c/$slug'
    | '/candidato/alertas'
    | '/candidato/candidaturas'
    | '/candidato/curriculo'
    | '/candidato/salvas'
    | '/candidato/vagas'
    | '/cv/$slug'
    | '/empresa/minhas-vagas'
    | '/empresa/nova-vaga'
    | '/empresa/pagina'
    | '/empresa/verificacao'
    | '/freelancer/orcamentos'
    | '/freelancer/perfil'
    | '/freelancer/portfolio'
    | '/preview/$style'
    | '/profissionais/$slug'
    | '/u/$handle'
    | '/vagas/$slug'
    | '/vagas/clt'
    | '/vagas/estagio'
    | '/vagas/pj'
    | '/admin'
    | '/blog'
    | '/candidato'
    | '/freelancer'
    | '/freelas'
    | '/preview'
    | '/vagas'
    | '/admin/blog/$id'
    | '/admin/blog/novo'
    | '/api/public/asaas-webhook'
    | '/api/public/migrate-sql'
    | '/api/public/painel-migracao'
    | '/api/public/track'
    | '/freelas/p/$handle'
    | '/api/public/blog/ingest'
    | '/api/public/cron/empresa-daily'
    | '/api/public/cron/gerar-post'
    | '/api/public/cron/reindex-google'
    | '/api/public/cron/reindex-vagas'
    | '/api/public/push/renew'
  id:
    | '__root__'
    | '/'
    | '/anuncie'
    | '/auth'
    | '/cadastro'
    | '/candidato'
    | '/categorias'
    | '/como-funciona'
    | '/contato'
    | '/empresa'
    | '/freelancer'
    | '/freelas'
    | '/para-empresas'
    | '/perfil'
    | '/planos'
    | '/privacidade'
    | '/reset-password'
    | '/sitemap.xml'
    | '/termos'
    | '/admin/anuncios'
    | '/admin/blog'
    | '/admin/usuarios'
    | '/admin/vagas'
    | '/admin/verificacoes'
    | '/blog/$slug'
    | '/c/$slug'
    | '/candidato/alertas'
    | '/candidato/candidaturas'
    | '/candidato/curriculo'
    | '/candidato/salvas'
    | '/candidato/vagas'
    | '/cv/$slug'
    | '/empresa/minhas-vagas'
    | '/empresa/nova-vaga'
    | '/empresa/pagina'
    | '/empresa/verificacao'
    | '/freelancer/orcamentos'
    | '/freelancer/perfil'
    | '/freelancer/portfolio'
    | '/preview/$style'
    | '/profissionais/$slug'
    | '/u/$handle'
    | '/vagas/$slug'
    | '/vagas/clt'
    | '/vagas/estagio'
    | '/vagas/pj'
    | '/admin/'
    | '/blog/'
    | '/candidato/'
    | '/freelancer/'
    | '/freelas/'
    | '/preview/'
    | '/vagas/'
    | '/admin/blog/$id'
    | '/admin/blog/novo'
    | '/api/public/asaas-webhook'
    | '/api/public/migrate-sql'
    | '/api/public/painel-migracao'
    | '/api/public/track'
    | '/freelas/p/$handle'
    | '/api/public/blog/ingest'
    | '/api/public/cron/empresa-daily'
    | '/api/public/cron/gerar-post'
    | '/api/public/cron/reindex-google'
    | '/api/public/cron/reindex-vagas'
    | '/api/public/push/renew'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnuncieRoute: typeof AnuncieRoute
  AuthRoute: typeof AuthRoute
  CadastroRoute: typeof CadastroRoute
  CandidatoRoute: typeof CandidatoRouteWithChildren
  CategoriasRoute: typeof CategoriasRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ContatoRoute: typeof ContatoRoute
  EmpresaRoute: typeof EmpresaRouteWithChildren
  FreelancerRoute: typeof FreelancerRouteWithChildren
  FreelasRoute: typeof FreelasRouteWithChildren
  ParaEmpresasRoute: typeof ParaEmpresasRoute
  PerfilRoute: typeof PerfilRoute
  PlanosRoute: typeof PlanosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosRoute: typeof TermosRoute
  AdminAnunciosRoute: typeof AdminAnunciosRoute
  AdminBlogRoute: typeof AdminBlogRouteWithChildren
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminVagasRoute: typeof AdminVagasRoute
  AdminVerificacoesRoute: typeof AdminVerificacoesRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CSlugRoute: typeof CSlugRoute
  CvSlugRoute: typeof CvSlugRoute
  PreviewStyleRoute: typeof PreviewStyleRoute
  ProfissionaisSlugRoute: typeof ProfissionaisSlugRoute
  UHandleRoute: typeof UHandleRoute
  VagasSlugRoute: typeof VagasSlugRoute
  VagasCltRoute: typeof VagasCltRoute
  VagasEstagioRoute: typeof VagasEstagioRoute
  VagasPjRoute: typeof VagasPjRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  PreviewIndexRoute: typeof PreviewIndexRoute
  VagasIndexRoute: typeof VagasIndexRoute
  ApiPublicAsaasWebhookRoute: typeof ApiPublicAsaasWebhookRoute
  ApiPublicMigrateSqlRoute: typeof ApiPublicMigrateSqlRoute
  ApiPublicPainelMigracaoRoute: typeof ApiPublicPainelMigracaoRoute
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
  ApiPublicBlogIngestRoute: typeof ApiPublicBlogIngestRoute
  ApiPublicCronEmpresaDailyRoute: typeof ApiPublicCronEmpresaDailyRoute
  ApiPublicCronGerarPostRoute: typeof ApiPublicCronGerarPostRoute
  ApiPublicCronReindexGoogleRoute: typeof ApiPublicCronReindexGoogleRoute
  ApiPublicCronReindexVagasRoute: typeof ApiPublicCronReindexVagasRoute
  ApiPublicPushRenewRoute: typeof ApiPublicPushRenewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-empresas': {
      id: '/para-empresas'
      path: '/para-empresas'
      fullPath: '/para-empresas'
      preLoaderRoute: typeof ParaEmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelas': {
      id: '/freelas'
      path: '/freelas'
      fullPath: '/freelas'
      preLoaderRoute: typeof FreelasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancer': {
      id: '/freelancer'
      path: '/freelancer'
      fullPath: '/freelancer'
      preLoaderRoute: typeof FreelancerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidato': {
      id: '/candidato'
      path: '/candidato'
      fullPath: '/candidato'
      preLoaderRoute: typeof CandidatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anuncie': {
      id: '/anuncie'
      path: '/anuncie'
      fullPath: '/anuncie'
      preLoaderRoute: typeof AnuncieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vagas/': {
      id: '/vagas/'
      path: '/vagas'
      fullPath: '/vagas/'
      preLoaderRoute: typeof VagasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/': {
      id: '/preview/'
      path: '/preview'
      fullPath: '/preview/'
      preLoaderRoute: typeof PreviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelas/': {
      id: '/freelas/'
      path: '/'
      fullPath: '/freelas/'
      preLoaderRoute: typeof FreelasIndexRouteImport
      parentRoute: typeof FreelasRoute
    }
    '/freelancer/': {
      id: '/freelancer/'
      path: '/'
      fullPath: '/freelancer/'
      preLoaderRoute: typeof FreelancerIndexRouteImport
      parentRoute: typeof FreelancerRoute
    }
    '/candidato/': {
      id: '/candidato/'
      path: '/'
      fullPath: '/candidato/'
      preLoaderRoute: typeof CandidatoIndexRouteImport
      parentRoute: typeof CandidatoRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vagas/pj': {
      id: '/vagas/pj'
      path: '/vagas/pj'
      fullPath: '/vagas/pj'
      preLoaderRoute: typeof VagasPjRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vagas/estagio': {
      id: '/vagas/estagio'
      path: '/vagas/estagio'
      fullPath: '/vagas/estagio'
      preLoaderRoute: typeof VagasEstagioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vagas/clt': {
      id: '/vagas/clt'
      path: '/vagas/clt'
      fullPath: '/vagas/clt'
      preLoaderRoute: typeof VagasCltRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vagas/$slug': {
      id: '/vagas/$slug'
      path: '/vagas/$slug'
      fullPath: '/vagas/$slug'
      preLoaderRoute: typeof VagasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profissionais/$slug': {
      id: '/profissionais/$slug'
      path: '/profissionais/$slug'
      fullPath: '/profissionais/$slug'
      preLoaderRoute: typeof ProfissionaisSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$style': {
      id: '/preview/$style'
      path: '/preview/$style'
      fullPath: '/preview/$style'
      preLoaderRoute: typeof PreviewStyleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancer/portfolio': {
      id: '/freelancer/portfolio'
      path: '/portfolio'
      fullPath: '/freelancer/portfolio'
      preLoaderRoute: typeof FreelancerPortfolioRouteImport
      parentRoute: typeof FreelancerRoute
    }
    '/freelancer/perfil': {
      id: '/freelancer/perfil'
      path: '/perfil'
      fullPath: '/freelancer/perfil'
      preLoaderRoute: typeof FreelancerPerfilRouteImport
      parentRoute: typeof FreelancerRoute
    }
    '/freelancer/orcamentos': {
      id: '/freelancer/orcamentos'
      path: '/orcamentos'
      fullPath: '/freelancer/orcamentos'
      preLoaderRoute: typeof FreelancerOrcamentosRouteImport
      parentRoute: typeof FreelancerRoute
    }
    '/empresa/verificacao': {
      id: '/empresa/verificacao'
      path: '/verificacao'
      fullPath: '/empresa/verificacao'
      preLoaderRoute: typeof EmpresaVerificacaoRouteImport
      parentRoute: typeof EmpresaRoute
    }
    '/empresa/pagina': {
      id: '/empresa/pagina'
      path: '/pagina'
      fullPath: '/empresa/pagina'
      preLoaderRoute: typeof EmpresaPaginaRouteImport
      parentRoute: typeof EmpresaRoute
    }
    '/empresa/nova-vaga': {
      id: '/empresa/nova-vaga'
      path: '/nova-vaga'
      fullPath: '/empresa/nova-vaga'
      preLoaderRoute: typeof EmpresaNovaVagaRouteImport
      parentRoute: typeof EmpresaRoute
    }
    '/empresa/minhas-vagas': {
      id: '/empresa/minhas-vagas'
      path: '/minhas-vagas'
      fullPath: '/empresa/minhas-vagas'
      preLoaderRoute: typeof EmpresaMinhasVagasRouteImport
      parentRoute: typeof EmpresaRoute
    }
    '/cv/$slug': {
      id: '/cv/$slug'
      path: '/cv/$slug'
      fullPath: '/cv/$slug'
      preLoaderRoute: typeof CvSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidato/vagas': {
      id: '/candidato/vagas'
      path: '/vagas'
      fullPath: '/candidato/vagas'
      preLoaderRoute: typeof CandidatoVagasRouteImport
      parentRoute: typeof CandidatoRoute
    }
    '/candidato/salvas': {
      id: '/candidato/salvas'
      path: '/salvas'
      fullPath: '/candidato/salvas'
      preLoaderRoute: typeof CandidatoSalvasRouteImport
      parentRoute: typeof CandidatoRoute
    }
    '/candidato/curriculo': {
      id: '/candidato/curriculo'
      path: '/curriculo'
      fullPath: '/candidato/curriculo'
      preLoaderRoute: typeof CandidatoCurriculoRouteImport
      parentRoute: typeof CandidatoRoute
    }
    '/candidato/candidaturas': {
      id: '/candidato/candidaturas'
      path: '/candidaturas'
      fullPath: '/candidato/candidaturas'
      preLoaderRoute: typeof CandidatoCandidaturasRouteImport
      parentRoute: typeof CandidatoRoute
    }
    '/candidato/alertas': {
      id: '/candidato/alertas'
      path: '/alertas'
      fullPath: '/candidato/alertas'
      preLoaderRoute: typeof CandidatoAlertasRouteImport
      parentRoute: typeof CandidatoRoute
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verificacoes': {
      id: '/admin/verificacoes'
      path: '/admin/verificacoes'
      fullPath: '/admin/verificacoes'
      preLoaderRoute: typeof AdminVerificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vagas': {
      id: '/admin/vagas'
      path: '/admin/vagas'
      fullPath: '/admin/vagas'
      preLoaderRoute: typeof AdminVagasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/admin/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/anuncios': {
      id: '/admin/anuncios'
      path: '/admin/anuncios'
      fullPath: '/admin/anuncios'
      preLoaderRoute: typeof AdminAnunciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelas/p/$handle': {
      id: '/freelas/p/$handle'
      path: '/p/$handle'
      fullPath: '/freelas/p/$handle'
      preLoaderRoute: typeof FreelasPHandleRouteImport
      parentRoute: typeof FreelasRoute
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/painel-migracao': {
      id: '/api/public/painel-migracao'
      path: '/api/public/painel-migracao'
      fullPath: '/api/public/painel-migracao'
      preLoaderRoute: typeof ApiPublicPainelMigracaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/migrate-sql': {
      id: '/api/public/migrate-sql'
      path: '/api/public/migrate-sql'
      fullPath: '/api/public/migrate-sql'
      preLoaderRoute: typeof ApiPublicMigrateSqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asaas-webhook': {
      id: '/api/public/asaas-webhook'
      path: '/api/public/asaas-webhook'
      fullPath: '/api/public/asaas-webhook'
      preLoaderRoute: typeof ApiPublicAsaasWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/novo': {
      id: '/admin/blog/novo'
      path: '/novo'
      fullPath: '/admin/blog/novo'
      preLoaderRoute: typeof AdminBlogNovoRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/api/public/push/renew': {
      id: '/api/public/push/renew'
      path: '/api/public/push/renew'
      fullPath: '/api/public/push/renew'
      preLoaderRoute: typeof ApiPublicPushRenewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/reindex-vagas': {
      id: '/api/public/cron/reindex-vagas'
      path: '/api/public/cron/reindex-vagas'
      fullPath: '/api/public/cron/reindex-vagas'
      preLoaderRoute: typeof ApiPublicCronReindexVagasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/reindex-google': {
      id: '/api/public/cron/reindex-google'
      path: '/api/public/cron/reindex-google'
      fullPath: '/api/public/cron/reindex-google'
      preLoaderRoute: typeof ApiPublicCronReindexGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/gerar-post': {
      id: '/api/public/cron/gerar-post'
      path: '/api/public/cron/gerar-post'
      fullPath: '/api/public/cron/gerar-post'
      preLoaderRoute: typeof ApiPublicCronGerarPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/empresa-daily': {
      id: '/api/public/cron/empresa-daily'
      path: '/api/public/cron/empresa-daily'
      fullPath: '/api/public/cron/empresa-daily'
      preLoaderRoute: typeof ApiPublicCronEmpresaDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/blog/ingest': {
      id: '/api/public/blog/ingest'
      path: '/api/public/blog/ingest'
      fullPath: '/api/public/blog/ingest'
      preLoaderRoute: typeof ApiPublicBlogIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CandidatoRouteChildren {
  CandidatoAlertasRoute: typeof CandidatoAlertasRoute
  CandidatoCandidaturasRoute: typeof CandidatoCandidaturasRoute
  CandidatoCurriculoRoute: typeof CandidatoCurriculoRoute
  CandidatoSalvasRoute: typeof CandidatoSalvasRoute
  CandidatoVagasRoute: typeof CandidatoVagasRoute
  CandidatoIndexRoute: typeof CandidatoIndexRoute
}

const CandidatoRouteChildren: CandidatoRouteChildren = {
  CandidatoAlertasRoute: CandidatoAlertasRoute,
  CandidatoCandidaturasRoute: CandidatoCandidaturasRoute,
  CandidatoCurriculoRoute: CandidatoCurriculoRoute,
  CandidatoSalvasRoute: CandidatoSalvasRoute,
  CandidatoVagasRoute: CandidatoVagasRoute,
  CandidatoIndexRoute: CandidatoIndexRoute,
}

const CandidatoRouteWithChildren = CandidatoRoute._addFileChildren(
  CandidatoRouteChildren,
)

interface EmpresaRouteChildren {
  EmpresaMinhasVagasRoute: typeof EmpresaMinhasVagasRoute
  EmpresaNovaVagaRoute: typeof EmpresaNovaVagaRoute
  EmpresaPaginaRoute: typeof EmpresaPaginaRoute
  EmpresaVerificacaoRoute: typeof EmpresaVerificacaoRoute
}

const EmpresaRouteChildren: EmpresaRouteChildren = {
  EmpresaMinhasVagasRoute: EmpresaMinhasVagasRoute,
  EmpresaNovaVagaRoute: EmpresaNovaVagaRoute,
  EmpresaPaginaRoute: EmpresaPaginaRoute,
  EmpresaVerificacaoRoute: EmpresaVerificacaoRoute,
}

const EmpresaRouteWithChildren =
  EmpresaRoute._addFileChildren(EmpresaRouteChildren)

interface FreelancerRouteChildren {
  FreelancerOrcamentosRoute: typeof FreelancerOrcamentosRoute
  FreelancerPerfilRoute: typeof FreelancerPerfilRoute
  FreelancerPortfolioRoute: typeof FreelancerPortfolioRoute
  FreelancerIndexRoute: typeof FreelancerIndexRoute
}

const FreelancerRouteChildren: FreelancerRouteChildren = {
  FreelancerOrcamentosRoute: FreelancerOrcamentosRoute,
  FreelancerPerfilRoute: FreelancerPerfilRoute,
  FreelancerPortfolioRoute: FreelancerPortfolioRoute,
  FreelancerIndexRoute: FreelancerIndexRoute,
}

const FreelancerRouteWithChildren = FreelancerRoute._addFileChildren(
  FreelancerRouteChildren,
)

interface FreelasRouteChildren {
  FreelasIndexRoute: typeof FreelasIndexRoute
  FreelasPHandleRoute: typeof FreelasPHandleRoute
}

const FreelasRouteChildren: FreelasRouteChildren = {
  FreelasIndexRoute: FreelasIndexRoute,
  FreelasPHandleRoute: FreelasPHandleRoute,
}

const FreelasRouteWithChildren =
  FreelasRoute._addFileChildren(FreelasRouteChildren)

interface AdminBlogRouteChildren {
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminBlogNovoRoute: typeof AdminBlogNovoRoute
}

const AdminBlogRouteChildren: AdminBlogRouteChildren = {
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminBlogNovoRoute: AdminBlogNovoRoute,
}

const AdminBlogRouteWithChildren = AdminBlogRoute._addFileChildren(
  AdminBlogRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnuncieRoute: AnuncieRoute,
  AuthRoute: AuthRoute,
  CadastroRoute: CadastroRoute,
  CandidatoRoute: CandidatoRouteWithChildren,
  CategoriasRoute: CategoriasRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ContatoRoute: ContatoRoute,
  EmpresaRoute: EmpresaRouteWithChildren,
  FreelancerRoute: FreelancerRouteWithChildren,
  FreelasRoute: FreelasRouteWithChildren,
  ParaEmpresasRoute: ParaEmpresasRoute,
  PerfilRoute: PerfilRoute,
  PlanosRoute: PlanosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosRoute: TermosRoute,
  AdminAnunciosRoute: AdminAnunciosRoute,
  AdminBlogRoute: AdminBlogRouteWithChildren,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminVagasRoute: AdminVagasRoute,
  AdminVerificacoesRoute: AdminVerificacoesRoute,
  BlogSlugRoute: BlogSlugRoute,
  CSlugRoute: CSlugRoute,
  CvSlugRoute: CvSlugRoute,
  PreviewStyleRoute: PreviewStyleRoute,
  ProfissionaisSlugRoute: ProfissionaisSlugRoute,
  UHandleRoute: UHandleRoute,
  VagasSlugRoute: VagasSlugRoute,
  VagasCltRoute: VagasCltRoute,
  VagasEstagioRoute: VagasEstagioRoute,
  VagasPjRoute: VagasPjRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  PreviewIndexRoute: PreviewIndexRoute,
  VagasIndexRoute: VagasIndexRoute,
  ApiPublicAsaasWebhookRoute: ApiPublicAsaasWebhookRoute,
  ApiPublicMigrateSqlRoute: ApiPublicMigrateSqlRoute,
  ApiPublicPainelMigracaoRoute: ApiPublicPainelMigracaoRoute,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
  ApiPublicBlogIngestRoute: ApiPublicBlogIngestRoute,
  ApiPublicCronEmpresaDailyRoute: ApiPublicCronEmpresaDailyRoute,
  ApiPublicCronGerarPostRoute: ApiPublicCronGerarPostRoute,
  ApiPublicCronReindexGoogleRoute: ApiPublicCronReindexGoogleRoute,
  ApiPublicCronReindexVagasRoute: ApiPublicCronReindexVagasRoute,
  ApiPublicPushRenewRoute: ApiPublicPushRenewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
