/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ParaEmpresasRouteImport } from './routes/para-empresas'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VagasSlugRouteImport } from './routes/vagas.$slug'
import { Route as EmpresaNovaVagaRouteImport } from './routes/empresa.nova-vaga'
import { Route as EmpresaMinhasVagasRouteImport } from './routes/empresa.minhas-vagas'
import { Route as CvSlugRouteImport } from './routes/cv.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaEmpresasRoute = ParaEmpresasRouteImport.update({
  id: '/para-empresas',
  path: '/para-empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VagasSlugRoute = VagasSlugRouteImport.update({
  id: '/vagas/$slug',
  path: '/vagas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaNovaVagaRoute = EmpresaNovaVagaRouteImport.update({
  id: '/nova-vaga',
  path: '/nova-vaga',
  getParentRoute: () => EmpresaRoute,
} as any)
const EmpresaMinhasVagasRoute = EmpresaMinhasVagasRouteImport.update({
  id: '/minhas-vagas',
  path: '/minhas-vagas',
  getParentRoute: () => EmpresaRoute,
} as any)
const CvSlugRoute = CvSlugRouteImport.update({
  id: '/cv/$slug',
  path: '/cv/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cadastro': typeof CadastroRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/empresa': typeof EmpresaRouteWithChildren
  '/para-empresas': typeof ParaEmpresasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cv/$slug': typeof CvSlugRoute
  '/empresa/minhas-vagas': typeof EmpresaMinhasVagasRoute
  '/empresa/nova-vaga': typeof EmpresaNovaVagaRoute
  '/vagas/$slug': typeof VagasSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cadastro': typeof CadastroRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/empresa': typeof EmpresaRouteWithChildren
  '/para-empresas': typeof ParaEmpresasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cv/$slug': typeof CvSlugRoute
  '/empresa/minhas-vagas': typeof EmpresaMinhasVagasRoute
  '/empresa/nova-vaga': typeof EmpresaNovaVagaRoute
  '/vagas/$slug': typeof VagasSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cadastro': typeof CadastroRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contato': typeof ContatoRoute
  '/empresa': typeof EmpresaRouteWithChildren
  '/para-empresas': typeof ParaEmpresasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cv/$slug': typeof CvSlugRoute
  '/empresa/minhas-vagas': typeof EmpresaMinhasVagasRoute
  '/empresa/nova-vaga': typeof EmpresaNovaVagaRoute
  '/vagas/$slug': typeof VagasSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cadastro'
    | '/como-funciona'
    | '/contato'
    | '/empresa'
    | '/para-empresas'
    | '/sitemap.xml'
    | '/cv/$slug'
    | '/empresa/minhas-vagas'
    | '/empresa/nova-vaga'
    | '/vagas/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cadastro'
    | '/como-funciona'
    | '/contato'
    | '/empresa'
    | '/para-empresas'
    | '/sitemap.xml'
    | '/cv/$slug'
    | '/empresa/minhas-vagas'
    | '/empresa/nova-vaga'
    | '/vagas/$slug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/cadastro'
    | '/como-funciona'
    | '/contato'
    | '/empresa'
    | '/para-empresas'
    | '/sitemap.xml'
    | '/cv/$slug'
    | '/empresa/minhas-vagas'
    | '/empresa/nova-vaga'
    | '/vagas/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CadastroRoute: typeof CadastroRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ContatoRoute: typeof ContatoRoute
  EmpresaRoute: typeof EmpresaRouteWithChildren
  ParaEmpresasRoute: typeof ParaEmpresasRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CvSlugRoute: typeof CvSlugRoute
  VagasSlugRoute: typeof VagasSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-empresas': {
      id: '/para-empresas'
      path: '/para-empresas'
      fullPath: '/para-empresas'
      preLoaderRoute: typeof ParaEmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vagas/$slug': {
      id: '/vagas/$slug'
      path: '/vagas/$slug'
      fullPath: '/vagas/$slug'
      preLoaderRoute: typeof VagasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa/nova-vaga': {
      id: '/empresa/nova-vaga'
      path: '/nova-vaga'
      fullPath: '/empresa/nova-vaga'
      preLoaderRoute: typeof EmpresaNovaVagaRouteImport
      parentRoute: typeof EmpresaRoute
    }
    '/empresa/minhas-vagas': {
      id: '/empresa/minhas-vagas'
      path: '/minhas-vagas'
      fullPath: '/empresa/minhas-vagas'
      preLoaderRoute: typeof EmpresaMinhasVagasRouteImport
      parentRoute: typeof EmpresaRoute
    }
    '/cv/$slug': {
      id: '/cv/$slug'
      path: '/cv/$slug'
      fullPath: '/cv/$slug'
      preLoaderRoute: typeof CvSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EmpresaRouteChildren {
  EmpresaMinhasVagasRoute: typeof EmpresaMinhasVagasRoute
  EmpresaNovaVagaRoute: typeof EmpresaNovaVagaRoute
}

const EmpresaRouteChildren: EmpresaRouteChildren = {
  EmpresaMinhasVagasRoute: EmpresaMinhasVagasRoute,
  EmpresaNovaVagaRoute: EmpresaNovaVagaRoute,
}

const EmpresaRouteWithChildren =
  EmpresaRoute._addFileChildren(EmpresaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CadastroRoute: CadastroRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ContatoRoute: ContatoRoute,
  EmpresaRoute: EmpresaRouteWithChildren,
  ParaEmpresasRoute: ParaEmpresasRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CvSlugRoute: CvSlugRoute,
  VagasSlugRoute: VagasSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
